# kitoneのRESTAPIを簡単に確認出来るよう作成
# TODO:チームメンバーにRESTclientをインストールするよう促す(6/18/0:42)

###
GET https://xd3utnv17sc2.cybozu.com/k/v1/records.json?app=5&id=1
X-Cybozu-API-Token: onEZOHK2ueJA5ldNinvNpz6ShgdEv0fOSBkWZacD

###
GET https://xd3utnv17sc2.cybozu.com/k/v1/record.json?app=6&id=1
X-Cybozu-API-Token: WDPSX1L5fSpI0gotEzB8ZjJyakVvCTs8trBJg7DY

###
GET https://xd3utnv17sc2.cybozu.com/k/v1/file.json?fileKey=201202061155587E339F9067544F1A92C743460E3D12B3297
X-Cybouzu-API-Token: WDPSX1L5fSpI0gotEzB8ZjJyakVvCTs8trBJg7DY
